"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    "back": "Back",
    "switch_lang": "Français",
    "hero_title": "Experience France with AI",
    "hero_subtitle": "A personalized digital trip to the heart of French culture. Learn, cook, explore, and dive into history through your unique AI companions.",
    "explore_agents": "Explore Your AI companions",
    "choose_guide": "Choose your AI guide to start your journey",
    "cta_button": "Start Your Adventure",
    
    // Moods
    "idle": "Active",
    "thinking": "Thinking...",
    "happy": "Happy",
    "listening": "Listening",
    "responding": "Speaking",
    
    // Pierre
    "pierre_title": "Chef Pierre's Cuisine Lab",
    "pierre_desc": "Cook authentic French dishes with a Michelin-star AI chef. Choose a regional specialty, select the perfect ingredients, and master the art of the perfect plate.",
    "pierre_tagline": "Mastering the Art of French Flavor",
    "pierre_map_title": "Interactive Culinary Map",
    "pierre_map_subtitle": "Hover over the map pins to discover regional specialties, then click to cook!",
    "pierre_dishes_title": "Regional Dishes of France",
    "pierre_dishes_subtitle": "Select a famous regional dish from the French Flag to learn how to cook it!",
    "pierre_change": "Change Dish",
    "pierre_facts_title": "Culinary Facts fr 🧢",
    "pierre_fact1": "France produces over 1,500 different types of cheese. The cheese lovers get it 😭.",
    "pierre_fact2": "The word 'Chef' just means 'Boss' in French. Big boss energy.",
    "pierre_fact3": "A traditional French meal is at least three courses. We feast here.",
    "pierre_fact4": "Croissants aren't even originally from France, they're from Austria (the Kipferl). Mind blown 🤯.",
    "pierre_fact5": "It's illegal to throw away unsold food in French supermarkets. W policy.",
    "pierre_build_dish": "Build Your French Dish",
    "pierre_select_dish": "Select a Regional Dish",
    "pierre_ingredients": "The Mixing Pot",
    "pierre_cook": "L'Art de la Cuisine (Cook!)",
    "pierre_reset": "Cook Another Dish",
    "pierre_success": "Magnifique! You successfully cooked",
    "pierre_hint_wrong": "You added something Pierre didn't like! Keep going.",
    "pierre_hint_correct": "Perfect additions! Keep going.",
    
    // Claire
    "claire_title": "Teacher Claire's Learn French",
    "claire_desc": "Learn French through interactive word puzzles and friendly conversation. From basic greetings to common phrases, Claire makes learning effortless and fun.",
    "claire_tagline": "Mastering the Art of Conversation",
    "claire_word_builder": "Word Builder",
    "claire_scrambled_hint": "Unscramble the letters to form a French greeting:",
    "claire_check": "Check",
    "claire_vocab": "Vocabulary Cards",
    "claire_correct": "Correct! It means",
    "claire_wrong": "Almost! Try again.",
    "claire_next": "Next Word",
    "claire_chat_welcome": "Bonjour! I'm Claire 👩‍🏫 Let’s learn French together — try saying *bonjour*!",
    "claire_chat_placeholder": "Learn French with Claire...",
    "claire_atelier_title": "Digital Atelier",
    "claire_atelier_subtitle": "Teacher Claire 🥐",
    "claire_word_builder_title": "Constructeur de Mots",
    "claire_verify_results": "Verify Results",
    "claire_vocab_daily": "Archives de Vocabulaire",
    "claire_vocab_subtitle": "Review words you've already encountered in the atelier.",
    "claire_crossword_title": "🧩 Mini Game: Crossword",
    "claire_grammar_title": "📚 French Grammar Essentials",
    "claire_verbs": "Verbes",
    "claire_possessive": "Possessive Adjectives",
    "claire_demonstrative": "Demonstrative",
    "claire_articles": "Articles",
    "claire_verbs_desc": "Conjugate common verbs like Être, Avoir, and Aller.",
    "claire_poss_desc": "Master ownership in French with gender-specific adjectives.",
    "claire_demon_desc": "Point things out using Ce, Cette, and Ces.",
    "claire_art_desc": "The building blocks of French sentences.",
    "claire_hint_claire": "Think of how you greet someone in French 😊",
    "claire_reveal_letter": "Reveal Letter",
    "claire_check_crossword": "Check Answers",
    
    // Louis
    "louis_title": "Guide Louis's Explore Paris",
    "louis_desc": "Explore Paris's most famous landmarks and plan your perfect trip. From the Eiffel Tower to hidden gems, Louis is your energetic guide to the city of light.",
    "louis_tagline": "Mastering the Art of Exploration",
    "louis_landmarks_title": "Explore Landmarks",
    "louis_landmark_subtitle": "Click a landmark to learn more.",
    "louis_landmark1_name": "Eiffel Tower",
    "louis_landmark1_info": "The iconic iron lattice tower built for the 1889 World's Fair. Global cultural icon of France.",
    "louis_landmark2_name": "Louvre Museum",
    "louis_landmark2_info": "The world's largest art museum and a historic monument in Paris. Home to the Mona Lisa.",
    "louis_landmark3_name": "Notre Dame",
    "louis_landmark3_info": "A medieval Catholic cathedral famous for its French Gothic architecture.",
    "louis_landmark4_name": "Arc de Triomphe",
    "louis_landmark4_info": "Honors those who fought and died for France in the French Revolutionary and Napoleonic Wars.",
    "louis_itinerary_title": "Plan Your Day",
    "louis_itinerary_subtitle": "Need help organizing your trip to Paris?",
    "louis_generate": "Generate Perfect Itinerary",
    "louis_itinerary_ready": "Your Custom Itinerary",
    "louis_itinerary1": "Morning: Visit the Louvre",
    "louis_itinerary2": "Lunch: Café on the Seine",
    "louis_itinerary3": "Afternoon: Explore Montmartre",
    "louis_itinerary4": "Evening: Sunset at the Eiffel Tower",

    "louis_transport_title": "Navigate the City Like a Local 🚇",
    "louis_metro": "Metro",
    "louis_tram": "Tram",
    "louis_bus": "Bus",
    "louis_live_timings": "Live Transport Timings 🕒",
    "louis_next_arrivals": "Next arrivals",
    "louis_view_full_map": "View Full Route Map",
    "louis_best_for": "Best for reaching",
    "louis_route": "Route",
    "louis_line": "Line",
    "louis_from": "From Station",
    "louis_to": "To Destination",
    "louis_find_route": "Find My Route",
    "louis_book_tickets": "Book Metro Tickets",
    "louis_buy_bus": "Buy Bus Tickets",
    "louis_view_pass": "View Transport Pass",
    "louis_official_site": "Official transport booking site",
    "louis_open_maps": "Open in Google Maps",
    "louis_arrival": "Next Arrival",
    "louis_platform": "Platform",
    "louis_destination": "Destination",

    // Cities Data
    "city_paris_name": "Paris",
    "city_paris_cat": "Capital / Culture",
    "city_paris_desc": "The City of Light, home to iconic landmarks and world-class museums.",
    "city_paris_food": "Ratatouille",
    "city_lyon_name": "Lyon",
    "city_lyon_cat": "Gastronomy / History",
    "city_lyon_desc": "Known as the Gastronomic Capital of France with a beautiful old town.",
    "city_lyon_food": "Quenelles",
    "city_nice_name": "Nice",
    "city_nice_cat": "Riviera / Coast",
    "city_nice_desc": "A stunning coastal city with pebble beaches and the famous Promenade des Anglais.",
    "city_nice_food": "Salade Niçoise",
    "city_marseille_name": "Marseille",
    "city_marseille_cat": "Port / Ancient",
    "city_marseille_desc": "France's oldest city, a vibrant port with a blend of cultures.",
    "city_marseille_food": "Bouillabaisse",
    
    // Landmarks
    "landmark_eiffel": "Eiffel Tower",
    "landmark_louvre": "Louvre",
    "landmark_rosiers": "Rue des Rosiers",
    "landmark_plantee": "Promenade Plantée",
    "landmark_fourviere": "Basilique Notre-Dame de Fourvière",
    "landmark_vieux_lyon": "Vieux Lyon",
    "landmark_halles": "Les Halles de Lyon",
    "landmark_promenade": "Promenade des Anglais",
    "landmark_castle": "Castle Hill",
    "landmark_saleya": "Cours Saleya",
    "landmark_vieux_port": "Vieux-Port",
    "landmark_garde": "Notre-Dame de la Garde",
    "landmark_panier": "The Panier District",
    
    // Amélie Artist Section
    "amelie_title": "Amélie's Creative Atelier",
    "amelie_desc": "Discover the soul of France through art, cinema, and melody. From Monet's gardens to the streets of Paris, Amélie guides you through the creative icons that define the nation.",
    "amelie_tagline": "The Creative Soul of France",
    "amelie_tab_paintings": "Paintings",
    "amelie_tab_films": "Films",
    "amelie_tab_music": "Music",
    "amelie_canvas_title": "Interactive Atelier",
    "amelie_canvas_desc": "Express your soul with Amélie's brush. Select a color and let your creativity flow through the heart of France.",
    "amelie_guess_painting": "Guess the Masterpiece",
    "amelie_guess_hint_hover": "Hover to reveal the masterpiece.",
    "amelie_seek_help": "Seek Help",
    "amelie_next": "Next",
    "amelie_expert_tip": "Expert Tip",
    "amelie_discover_story": "Discover Story",
    "amelie_explore_bios": "Explore Artist Bios",
    "amelie_painters_title": "Famous French Painters",
    "amelie_painters_desc": "From the light of Giverny to the revolutionary murals of Paris, meet the masters who redefined the vision of the world.",
    "amelie_monet_desc": "The master of light. Found eternity in his pond at Giverny.",
    "amelie_monet_fact": "He painted the same lilies over 250 times to capture light's movement.",
    "amelie_delacroix_desc": "A visionary of intense drive, famous for vibrant colors and grand emotional drama.",
    "amelie_delacroix_fact": "His 'Liberty Leading the People' became a symbol of the French Republic.",
    "amelie_picasso_desc": "Spanish-born genius but the heart of the 'School of Paris'. Shattered the perspective.",
    "amelie_picasso_fact": "He co-founded Cubism and remained the most influential artist of the 20th century.",
    "amelie_film_vibe": "Artistic Vibe",
    "amelie_film_culture": "Cultural Soul",
    "amelie_music_lyrics": "Lyric Wisdom",
    "amelie_lyrics_pron": "Speak like a poet",
    "amelie_guess_placeholder": "Identify this masterpiece...",
    "amelie_correct": "C'est magnifique! You have an artist's eye.",
    "amelie_wrong": "Not quite, but every stroke is a lesson. Try again!",
    "amelie_film_amelie": "Amélie",
    "amelie_film_haine": "La Haine",
    "amelie_film_intouchables": "Intouchables",
    "amelie_artist_monet": "Claude Monet",
    "amelie_artist_vangogh": "Van Gogh",
    "amelie_artist_picasso": "Picasso",
    
    // Chat
    "chat_welcome": "Bonjour! I am {displayName}. Ask me anything about {topic}.",
    "chat_placeholder": "Ask {shortName} about {topic}...",
    "chat_error": "Désolé, I'm having trouble responding. Please try again!",
    "chat_with": "Chat with",
    "chat_companion": "companion",
    "chat_studio": "Studio",
    "chat_history": "Legendary Historian",
    "chat_guide": "Paris Explorer",
    "chat_culinary": "Culinary Legend",
    "louis_guide_suffix": "Explorer",

    // Louis Hero
    "louis_tagline_hero": "Guide Louis at your service",
    "louis_hero_h1": "Explore France",
    "louis_hero_h1_span": "With Louis 🇫🇷",
    "louis_hero_p": "From the bustling streets of Paris to the sunny shores of the Riviera, let's discover the real France together.",
    "louis_start_exploring": "Start Exploring",
    "louis_plan_trip": "Plan My Trip",
    
    // UI Elements
    "ui_local_dish": "Local Dish",
    "ui_loading_map": "Loading Map...",
    "ui_init_metro": "Initializing Metro Map...",
    "ui_planner_title": "Smart Trip Planner",
    "ui_planner_gen": "Generate Perfect Itinerary",
    "ui_footer_name": "Louis Guide Co.",
    "ui_footer_est": "Est. 2026 • AI Powered Travel",
    
    // Nav
    "nav_map": "Map",
    "nav_cities": "Cities",
    "nav_planner": "Planner",
    "nav_tips": "Tips",
  },
  fr: {
    // General
    "back": "Retour",
    "switch_lang": "English",
    "hero_title": "Découvrez la France avec l'IA",
    "hero_subtitle": "Un voyage numérique personnalisé au cœur de la culture française. Apprenez, cuisinez, explorez et plongez dans l'histoire grâce à vos compagnons IA uniques.",
    "explore_agents": "Explorez vos compagnons IA",
    "choose_guide": "Choisissez votre guide IA pour commencer votre voyage",
    "cta_button": "Commencer l'Aventure",
    
    // Moods
    "idle": "Actif",
    "thinking": "Réflexion...",
    "happy": "Souriant",
    "listening": "À l'écoute",
    "responding": "Réponse en cours",
    
    // Pierre
    "pierre_title": "Le Laboratoire Culinaire du Chef Pierre",
    "pierre_desc": "Cuisinez des plats français authentiques avec un chef IA étoilé au guide Michelin. Choisissez une spécialité régionale, sélectionnez les ingrédients parfaits et maîtrisez l'art de l'assiette parfaite.",
    "pierre_tagline": "Maîtriser l'Art des Saveurs Françaises",
    "pierre_map_title": "Carte Culinaire Interactive",
    "pierre_map_subtitle": "Survolez les points pour découvrir les spécialités, puis cliquez pour cuisiner !",
    "pierre_dishes_title": "Plats Régionaux de France",
    "pierre_dishes_subtitle": "Choisissez un plat célèbre pour apprendre à le cuisiner !",
    "pierre_change": "Changer de plat",
    "pierre_facts_title": "Faits Culinaires 🧢",
    "pierre_fact1": "La France produit plus de 1 500 types de fromages différents. Les amoureux du fromage savent 😭.",
    "pierre_fact2": "Le mot 'Chef' signifie simplement 'Patron'. Une énergie de patron.",
    "pierre_fact3": "Un repas français traditionnel comporte au moins trois plats. C'est un festin.",
    "pierre_fact4": "Les croissants ne viennent pas de France, mais d'Autriche (le Kipferl). Incroyable 🤯.",
    "pierre_fact5": "Il est illégal de jeter les invendus alimentaires en France. Belle politique.",
    "pierre_build_dish": "Créez votre plat français",
    "pierre_select_dish": "Sélectionnez un plat régional",
    "pierre_ingredients": "La Marmite (Ingrédients)",
    "pierre_cook": "L'Art de la Cuisine (Cuisiner !)",
    "pierre_reset": "Cuisiner un autre plat",
    "pierre_success": "Magnifique ! Vous avez réussi à cuisiner",
    "pierre_hint_wrong": "Vous avez ajouté quelque chose que Pierre n'a pas aimé ! Continuez.",
    "pierre_hint_correct": "Ajouts parfaits ! Continuez.",
    
    // Claire
    "claire_title": "Apprenez le français avec Claire",
    "claire_desc": "Apprenez le français grâce à des puzzles de mots interactifs et des conversations amicales. Des salutations de base aux phrases courantes, Claire rend l'apprentissage facile et amusant.",
    "claire_tagline": "Maîtriser l'Art de la Conversation",
    "claire_word_builder": "Constructeur de mots",
    "claire_scrambled_hint": "Démêlez les lettres pour former une salutation française :",
    "claire_check": "Vérifier",
    "claire_vocab": "Cartes de vocabulaire",
    "claire_correct": "Correct ! Cela signifie",
    "claire_wrong": "Presque ! Réessayez.",
    "claire_next": "Mot suivant",
    "claire_chat_welcome": "Bonjour ! Je suis Claire 👩‍🏫 Apprenons le français ensemble — essayez de dire *bonjour* !",
    "claire_chat_placeholder": "Apprendre le français avec Claire...",
    "claire_atelier_title": "Atelier Numérique",
    "claire_atelier_subtitle": "Professeur Claire 🥐",
    "claire_word_builder_title": "Constructeur de Mots",
    "claire_verify_results": "Vérifier les résultats",
    "claire_vocab_daily": "Archives de Vocabulaire",
    "claire_vocab_subtitle": "Révisez les mots que vous avez déjà rencontrés dans l'atelier.",
    "claire_crossword_title": "🧩 Mini-Jeu : Mots Croisés",
    "claire_grammar_title": "📚 L'Essentiel de la Grammaire",
    "claire_verbs": "Verbes",
    "claire_possessive": "Adjectifs Possessifs",
    "claire_demonstrative": "Démonstratifs",
    "claire_articles": "Articles",
    "claire_verbs_desc": "Conjuguez les verbes courants comme Être, Avoir et Aller.",
    "claire_poss_desc": "Maîtrisez la possession en français.",
    "claire_demon_desc": "Désignez des objets avec Ce, Cette et Ces.",
    "claire_art_desc": "Les piliers de la phrase française.",
    "claire_hint_claire": "Pensez à la façon dont vous saluez quelqu'un en français 😊",
    "claire_reveal_letter": "Révéler une lettre",
    "claire_check_crossword": "Vérifier les réponses",
    
    // Louis
    "louis_title": "Explorez Paris avec Louis",
    "louis_desc": "Explorez les monuments les plus célèbres de Paris et planifiez votre voyage parfait. De la Tour Eiffel aux joyaux cachés, Louis est votre guide énergique dans la ville lumière.",
    "louis_tagline": "Maîtriser l'Art de l'Exploration",
    "louis_landmarks_title": "Explorer les Monuments",
    "louis_landmark_subtitle": "Cliquez sur un monument pour en savoir plus.",
    "louis_landmark1_name": "Tour Eiffel",
    "louis_landmark1_info": "La tour emblématique construite pour l'Exposition Universelle de 1889. Symbole de la France.",
    "louis_landmark2_name": "Musée du Louvre",
    "louis_landmark2_info": "Le plus grand musée d'art au monde. Domicile de la Joconde.",
    "louis_landmark3_name": "Notre-Dame",
    "louis_landmark3_info": "Cathédrale médiévale célèbre pour son architecture gothique française.",
    "louis_landmark4_name": "Arc de Triomphe",
    "louis_landmark4_info": "Honore ceux qui ont combattu pour la France pendant la Révolution et l'Empire.",
    "louis_itinerary_title": "Planifiez votre journée",
    "louis_itinerary_subtitle": "Besoin d'aide pour organiser votre visite ?",
    "louis_generate": "Générer l'itinéraire parfait",
    "louis_itinerary_ready": "Votre itinéraire personnalisé",
    "louis_itinerary1": "Matin : Visite du Louvre",
    "louis_itinerary2": "Midi : Déjeuner sur la Seine",
    "louis_itinerary3": "Après-midi : Exploration de Montmartre",
    "louis_itinerary4": "Soir : Coucher de soleil à la Tour Eiffel",

    "louis_transport_title": "Naviguez comme un local 🚇",
    "louis_metro": "Métro",
    "louis_tram": "Tramway",
    "louis_bus": "Bus",
    "louis_live_timings": "Horaires en temps réel 🕒",
    "louis_next_arrivals": "Prochains passages",
    "louis_view_full_map": "Voir le plan complet",
    "louis_best_for": "Idéal pour aller à",
    "louis_route": "Ligne",
    "louis_line": "Ligne",
    "louis_from": "Station de départ",
    "louis_to": "Destination",
    "louis_find_route": "Trouver mon trajet",
    "louis_book_tickets": "Réserver des billets",
    "louis_buy_bus": "Acheter des billets de bus",
    "louis_view_pass": "Voir le pass transport",
    "louis_official_site": "Site de réservation officiel",
    "louis_open_maps": "Ouvrir dans Google Maps",
    "louis_arrival": "Arrivée",
    "louis_platform": "Quai",
    "louis_destination": "Destination",

    // Cities Data
    "city_paris_name": "Paris",
    "city_paris_cat": "Capitale / Culture",
    "city_paris_desc": "La Ville Lumière, foyer de monuments emblématiques et de musées de classe mondiale.",
    "city_paris_food": "Ratatouille",
    "city_lyon_name": "Lyon",
    "city_lyon_cat": "Gastronomie / Histoire",
    "city_lyon_desc": "Connue comme la capitale gastronomique de la France avec une magnifique vieille ville.",
    "city_lyon_food": "Quenelles",
    "city_nice_name": "Nice",
    "city_nice_cat": "Riviera / Côte d'Azur",
    "city_nice_desc": "Une ville côtière époustouflante avec des plages de galets et la célèbre Promenade des Anglais.",
    "city_nice_food": "Salade Niçoise",
    "city_marseille_name": "Marseille",
    "city_marseille_cat": "Port / Antique",
    "city_marseille_desc": "La plus ancienne ville de France, un port vibrant aux cultures métissées.",
    "city_marseille_food": "Bouillabaisse",

    // Landmarks
    "landmark_eiffel": "Tour Eiffel",
    "landmark_louvre": "Louvre",
    "landmark_rosiers": "Rue des Rosiers",
    "landmark_plantee": "Promenade Plantée",
    "landmark_fourviere": "Basilique Notre-Dame de Fourvière",
    "landmark_vieux_lyon": "Vieux Lyon",
    "landmark_halles": "Les Halles de Lyon",
    "landmark_promenade": "Promenade des Anglais",
    "landmark_castle": "Colline du Château",
    "landmark_saleya": "Cours Saleya",
    "landmark_vieux_port": "Vieux-Port",
    "landmark_garde": "Notre-Dame de la Garde",
    "landmark_panier": "Le Panier",
    
    // Amélie Artist Section
    "amelie_title": "L'Atelier Créatif d'Amélie",
    "amelie_desc": "Découvrez l'âme de la France à travers l'art, le cinéma et la mélodie. Des jardins de Monet aux rues de Paris, Amélie vous guide à travers les icônes créatives qui définissent la nation.",
    "amelie_tagline": "L'Âme Créative de la France",
    "amelie_tab_paintings": "Peinture",
    "amelie_tab_films": "Films",
    "amelie_tab_music": "Musique",
    "amelie_canvas_title": "Atelier Interactif",
    "amelie_canvas_desc": "Exprimez votre âme avec le pinceau d'Amélie. Choisissez une couleur et laissez votre créativité couler au cœur de la France.",
    "amelie_guess_painting": "Devinez le Chef-d'œuvre",
    "amelie_guess_hint_hover": "Survolez pour révéler le chef-d'œuvre.",
    "amelie_seek_help": "Chercher de l'Aide",
    "amelie_next": "Suivant",
    "amelie_expert_tip": "Conseil d'Expert",
    "amelie_discover_story": "Découvrir l'Histoire",
    "amelie_explore_bios": "Explorer les Bios d'Artistes",
    "amelie_painters_title": "Peintres Français Célèbres",
    "amelie_painters_desc": "De la lumière de Giverny aux fresques révolutionnaires de Paris, découvrez les maîtres qui ont redéfini la vision du monde.",
    "amelie_monet_desc": "Le maître de la lumière. A trouvé l'éternité dans son étang de Giverny.",
    "amelie_monet_fact": "Il a peint les mêmes nénuphars plus de 250 fois pour capturer le mouvement de la lumière.",
    "amelie_delacroix_desc": "Un visionnaire au dynamisme intense, célèbre pour ses couleurs vibrantes et son grand drame émotionnel.",
    "amelie_delacroix_fact": "Sa 'Liberté guidant le peuple' est devenue un symbole de la République française.",
    "amelie_picasso_desc": "Génie d'origine espagnole, mais cœur de l'École de Paris. A brisé la perspective.",
    "amelie_picasso_fact": "Il a cofondé le cubisme et est resté l'artiste le plus influent du XXe siècle.",
    "amelie_film_vibe": "Ambiance Artistique",
    "amelie_film_culture": "Âme Culturelle",
    "amelie_music_lyrics": "Sagesse des Paroles",
    "amelie_lyrics_pron": "Parlez comme un poète",
    "amelie_guess_placeholder": "Identifiez ce chef-d'œuvre...",
    "amelie_correct": "C'est magnifique ! Vous avez l'œil d'un artiste.",
    "amelie_wrong": "Pas tout à fait, mais chaque trait est une leçon. Réessayez !",
    "amelie_film_amelie": "Le Fabuleux Destin d'Amélie Poulain",
    "amelie_film_haine": "La Haine",
    "amelie_film_intouchables": "Intouchables",
    "amelie_artist_monet": "Claude Monet",
    "amelie_artist_vangogh": "Van Gogh",
    "amelie_artist_picasso": "Picasso",
    
    // Chat
    "chat_welcome": "Bonjour ! Je suis {displayName}. Posez-moi vos questions sur {topic}.",
    "chat_placeholder": "Demandez à {shortName} sur {topic}...",
    "chat_error": "Désolé, j'ai du mal à répondre. Veuillez réessayer !",
    "chat_with": "Discuter avec",
    "chat_companion": "compagnon",
    "chat_studio": "Studio",
    "chat_history": "Historienne légendaire",
    "chat_guide": "Explorateur de Paris",
    "chat_culinary": "Légende culinaire",
    "louis_guide_suffix": "Explorateur",

    // Louis Hero
    "louis_tagline_hero": "Guide Louis à votre service",
    "louis_hero_h1": "Explorez la France",
    "louis_hero_h1_span": "Avec Louis 🇫🇷",
    "louis_hero_p": "Des rues animées de Paris aux rivages ensoleillés de la Côte d'Azur, découvrons ensemble la vraie France.",
    "louis_start_exploring": "Commencer l'exploration",
    "louis_plan_trip": "Planifier mon voyage",

    // UI Elements
    "ui_local_dish": "Plat Local",
    "ui_loading_map": "Chargement de la carte...",
    "ui_init_metro": "Initialisation du plan du métro...",
    "ui_planner_title": "Planificateur de Voyage",
    "ui_planner_gen": "Générer l'Itinéraire Parfait",
    "ui_footer_name": "Louis Guide Co.",
    "ui_footer_est": "Brève de 2026 • Voyage par l'IA",

    // Nav
    "nav_map": "Carte",
    "nav_cities": "Villes",
    "nav_planner": "Planificateur",
    "nav_tips": "Astuces",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
